import Config

# Configure your database
config :oneagent, OneAgent.Repo,
  username: "dpenny",
  password: "",
  hostname: "localhost",
  database: "oneagent_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :oneagent, OneAgentWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Dkstvvt9PsOTSUgm9iCAPCdJhp2TMk/t1MjjXijfhZw4IvH09qTCuB9xx5Jo7y1h",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :oneagent, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Use Resend for real email delivery in dev
config :oneagent, OneAgent.Mailer,
  adapter: Swoosh.Adapters.Resend,
  api_key: System.get_env("RESEND_API_KEY", "")

config :swoosh, :api_client, Swoosh.ApiClient.Finch

# Cloak encryption key for development (NOT for production use)
config :oneagent, OneAgent.Vault,
  ciphers: [
    default: {Cloak.Ciphers.AES.GCM,
     tag: "AES.GCM.V1",
     key: Base.decode64!("QmSD1PV9odxXZgMv43Xp2/7601+w+3JBQ1kHWVnyQ44=")}
  ]
