defmodule OneAgentWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :oneagent

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_oneagent_key",
    signing_salt: "089dWjLW",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :oneagent,
    gzip: not code_reloading?,
    only: OneAgentWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :oneagent
  end

  plug Corsica,
    origins: {OneAgentWeb.Endpoint, :cors_origins, []},
    allow_headers: ["authorization", "content-type"],
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_credentials: true

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {OneAgentWeb.Plugs.CacheRawBody, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug OneAgentWeb.Router

  def cors_origins(_conn, origin) do
    allowed =
      case Application.get_env(:oneagent, :cors_origin) do
        nil -> ["http://localhost:3000"]
        o when is_binary(o) -> [o]
        origins when is_list(origins) -> origins
      end

    origin in allowed
  end
end
